exclude: ^(.*\/migrations|.*package.json|.*package-lock.json|Pipfile*)
repos:
# COMMON
- hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: forbid-new-submodules
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
  repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
- hooks:
  - id: check-json
  - args:
    - --autofix
    id: pretty-format-json
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: beautysh
  repo: https://github.com/bemeurer/beautysh.git
  rev: v6.2.1
- hooks:
  - id: script-must-have-extension
  repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
- hooks:
  - id: check-xml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - args:
    - '-d {rules: {line-length: {max: 999}}}'
    id: yamllint
  repo: https://github.com/adrienverge/yamllint.git
  rev: v1.30.0
- hooks:
  - id: check-yaml
  - id: sort-simple-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: gitlab-ci-linter
  repo: https://gitlab.com/devopshq/gitlab-ci-linter
  rev: v1.0.3

# PYTHON
- hooks:
  - id: check-ast
    language_version: python3.8
  - id: check-builtin-literals
    language_version: python3.8
  - id: check-docstring-first
    language_version: python3.8
  - id: debug-statements
    language_version: python3.8
  - args:
    - --remove
    id: fix-encoding-pragma
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
- hooks:
  - id: black
    language_version: python3.8
  repo: https://github.com/ambv/black
  rev: 23.3.0
- hooks:
  - args:
    - --config=.flake8
    id: flake8
    language_version: python3.8
  repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
- hooks:
  - id: python-safety-dependencies-check
  repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.1
