---

- hosts: all
  vars:
    - logs_base_path: /var/log/nginx/oxfam
    - public_hostname: oxfam-pdg-cac40.tlscp.fr
    - project_slug: "oxfam-pdg-cac40"
    - static_path: /telescoop/oxfam-pdg-cac40/static

  remote_user: root
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

  tasks:
    - name: make sure log folder exists
      file:
        path: "{{ logs_base_path }}"
        state: directory
        mode: '755'

    - name: Copy nginx config
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-enabled/{{ project_slug }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Make sure static folder exists
      file:
        path: "{{ static_path }}"
        state: directory
        owner: www-data

    - name: Upload static files
      copy:
        src: "../{{ item }}"
        dest: "{{ static_path }}/"
        owner: www-data
      loop:
        - js
        - css
        - images
        - logos
        - fonts
        - index.html
