---

- hosts: all
  vars:
    - logs_base_path: /var/log/nginx/oxfam
    - public_hostname: oxfam-mega-bouses.tlscp.fr
    - project_slug: "oxfam-mega-bouses"
    - static_path: /telescoop/mega-bouses/static
    - script_path: /telescoop/mega-bouses/parse_logs.py
    - statistics_page: "{{ static_path }}/wjgtswwxcf2.html"
  remote_user: root
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

  tasks:
    - name: make sure log folder exists
      file:
        path: "{{ logs_base_path }}"
        state: directory
        mode: '755'

    - name: Copy nginx config
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-enabled/{{ project_slug }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Make sure static folder exists
      file:
        path: "{{ static_path }}"
        state: directory
        owner: www-data

    - name: Upload static files
      copy:
        src: "../{{ item }}"
        dest: "{{ static_path }}/"
        owner: www-data
      loop:
        - js
        - css
        - images
        - logos
        - fonts
        - index.html
        - ex-integration.html

    - name: Upload python script
      template:
        src: "../parse_logs/parse_logs.py"
        dest: "{{ script_path }}"

    - name: "Cron - parse logs regularly"
      cron:
        name: 'parse nginx logs and generate static file'
        minute: "32"
        job: "STATISTIC_PAGE_PATH={{ statistics_page }} python3 {{ script_path }}"

    - name: Parse logs now
      command:
        cmd: "python3 {{ script_path }}"
      environment:
        STATISTIC_PAGE_PATH: "{{ statistics_page }}"
